### ISSUE TITLE
Potentially exposed private key

### ISSUE THREAD

**Issue by tslater2006** [HouseHold/HouseHold#6]
You've got what looks to be an exposed private key here: https://github.com/HouseHold/HouseHold/blob/master/config/jwt/private.pem

Consider changing your credentials and leveraging environment variables so they don't end up online.

Credentials were spotted by https://shhgit.darkport.co.uk/

**Comment by NikoGrano** [comment]
Hey!

It's there on purpose. This same JWT files are in many other public and well-known project exposed. The files are considered as development related.

There is even passphrase exposed at https://github.com/HouseHold/HouseHold/blob/master/.env and it is `development`, that should be a hint about this.

Anyways, thank you for you report and your work. Closing this as Invalid.

**Comment by tslater2006** [comment]
Thanks for the reply. I'm not related to the shhgit project but I was checking them out and this popped up. Figured I'd rather let you know and it be a non issue than the other way around. :)
